cmd/release: avoid temporary conflicts when moving issues to projects
Hopefully, with a retry we will avoid these issues during the release
process:

> Error: unable to add PR 42407 to project cilium v1.16.17:
> Your attempt to move this item created a temporary conflict. Please try again.

Signed-off-by: André Martins <andre@cilium.io>