fix golang build
It's currently not possible to build this repository. This commit fixes
the build.

cmd/projects/projects.go:205:7: undefined: repoName
cmd/projects/projects.go:205:17: undefined: prNmuber

Fixes: 2a086b71ee4e ("Avoid moving pending backports to new project")
Signed-off-by: André Martins <andre@cilium.io>